##⇘⇘ This file is left blank
## Old content has been categorized and moved to the following files:
## input_easy.conf
## input_list.conf
## input_scripts.conf

## Standard Key Names (Non-exhaustive list)
## Mouse Button Series:
##   MBTN_LEFT   MBTN_RIGHT   MBTN_MID   MBTN_FORWARD   MBTN_BACK   WHEEL_UP   WHEEL_DOWN   WHEEL_LEFT   WHEEL_RIGHT
## Lowercase Letters/Numbers Series:
##   q   w   e   r ... 1   2   3   4 ...
## Uppercase Letters/Symbols Series:
##   Q   W   E   R ... !   @   SHARP   $ ...
## Numpad Series:
##   KP1   KP2   KP3   KP_DEC   KP_ENTER   KP_ADD   KP_SUBTRACT   KP_MULTIPLY   KP_DIVIDE ...
## Independent Modifier/Function Key Series:
##   UP   DOWN   LEFT   RIGHT   ESC   TAB   BS   SPACE   HOME   END   PGUP   PGDWN   DEL ...
## Modifier/Function Keys (Must be used in combination):
##   Shift+   Ctrl+   Alt+   Shift+Ctrl+   Shift+Alt+   Ctrl+Alt+   Shift+Ctrl+Alt+ ...
## Double-click/Multi-key Binding Series:
##   MBTN_LEFT_DBL   MBTN_RIGHT_DBL   MBTN_MID_DBL   q-q   q-w   q-w-e   q-w-e-r ...
