##⇘⇘ This file demonstrates the syntax for uosc.lua's built-in context menu
## Commands prefixed with uosc/ are internal functions. 
## For more available commands, visit: https://github.com/tomasklaen/uosc/blob/main/README.md#commands
## This syntax is specific to uosc and does not work in standard mpv input.conf

#                   script-binding uosc/open-file                         #! Load > ※ File Browser
#                   script-binding uosc/load-subtitles                    #! Load > ※ Import Subtitles

#                   script-binding uosc/playlist                          #! Navigation > ※ Playlist
#                   script-binding uosc/editions                          #! Navigation > ※ Editions List
#                   script-binding uosc/chapters                          #! Navigation > ※ Chapters List
#                   script-binding uosc/video                             #! Navigation > ※ Video Tracks
#                   script-binding uosc/audio                             #! Navigation > ※ Audio Tracks
#                   script-binding uosc/subtitles                         #! Navigation > ※ Subtitle Tracks
#                   playlist-shuffle                                      #! Navigation > Shuffle Playlist

#                   screenshot scaled+subtitles                            #! Screenshot (with Subs, no OSD)

#                   cycle-values hwdec "auto" "auto-copy" "no"             #! Video > Toggle HW Decoding
#                   cycle deband                                          #! Video > Toggle Debanding
#                   cycle deinterlace                                     #! Video > Toggle Deinterlacing
#                   cycle icc-profile-auto                                #! Video > Toggle Auto Color Calibration
#                   cycle correct-pts                                     #! Video > Toggle PTS Mode

#                   script-binding uosc/keybinds                          #! Tools > ※ Keybindings List
#                   script-binding display-stats-toggle                   #! Tools > Toggle Stats Overlay
#                   script-binding commands/open                          #! Tools > Show Console
#                   cycle border                                          #! Tools > Toggle Window Border
#                   cycle ontop                                           #! Tools > Toggle Stay-on-Top
#                   script-binding uosc/audio-device                      #! Tools > ※ Audio Devices
#                   script-binding uosc/stream-quality                    #! Tools > ※ Stream Quality
#                   script-binding uosc/show-in-directory                 #! Tools > ※ Open File Location
#                   script-binding uosc/open-config-directory             #! Tools > ※ Open Config Folder

#                   stop                                                  #! Stop
#                   quit                                                  #! Quit MPV
